gpn-prototypes/vega-header

.github/kuberta.yaml, .github/workflows/build-static.yaml, package.json, webpack.forShellConfig.js, yarn.lock
=> VEGA-434: Настроить деплой vega-header

.github/workflows/update-pr.yaml
Cсылка в Jira CSSSR на задачу: https://jira.csssr.io/browse/VEGA-512
Ссылка на скрипт http://VEGA-512.vega-header.csssr.cloud/vega-header.js
=> Добавить ссылку на скрипт

webpack.forShellConfig.js
=> VEGA-505: Разобраться с подключением vega-ui в обвязке

package.json, src/App/App.tsx, webpack.forShellConfig.js, yarn.lock
=> VEGA-504: Настроить сборку общих зависимостей в vega-shell

src/components/Header/Header.tsx, src/components/Header/get-project-name.graphql
=> Фикс работы с клиентом 

webpack.forShellConfig.js
Cсылка в Jira CSSSR на задачу: https://jira.csssr.io/browse/VEGA-630
Ссылка на скрипт http://VEGA-630.vega-header.csssr.cloud/vega-header.js
=> VEGA-630: Прокинуть переменные окружения в сборку

src/components/Header/HeaderView.tsx
Cсылка в Jira CSSSR на задачу: https://jira.csssr.io/browse/VEGA-2601
Ссылка на скрипт http://VEGA-2601.vega-header.csssr.cloud/vega-header.js
https://jira.konakov.tv/browse/VEGA-2601
Добавлен пункт в навигации "Логика проекта" для перехода к КЛ
* пересоздал - ветка без feature
=> VEGA-2601: Интеграция vega-lc в vega-shell

src/components/BaseHeader/BaseHeader.css
Cсылка в Jira CSSSR на задачу: https://jira.csssr.io/browse/VEGA-707
Ссылка на скрипт http://VEGA-707.vega-header.csssr.cloud/vega-header.js
Jira issue: VEGA-707
=> VEGA-707: [В МАСТЕР] Исправить хедер в РБ

package.json, yarn.lock
=> Откатил webpack-cli (ломает dev server)

app-config/index.js, codegen.yml, src/App/index.tsx, webpack.forShellConfig.js
Cсылка в Jira CSSSR на задачу: https://jira.csssr.io/browse/VEGA-719
Ссылка на скрипт http://VEGA-719.vega-header.csssr.cloud/vega-header.js
=> VEGA-719: Избавиться от упоминаний стендов в репозиториях

src/components/BaseHeader/BaseHeader.css, src/components/BaseHeader/BaseHeaderMenu/BaseHeaderMenu.test.tsx, src/components/BaseHeader/BaseHeaderMenu/BaseHeaderMenu.tsx, src/components/BaseHeader/BaseHeaderMenu/BaseHeaderMenuDelimiter.tsx, src/components/BaseHeader/BaseHeaderNav/BaseHeaderNav.tsx, src/components/BaseHeader/Header.test.tsx, src/components/Header/Header.css, src/components/Header/HeaderView.tsx
Cсылка в Jira CSSSR на задачу: https://jira.csssr.io/browse/VEGA-627
Ссылка на скрипт http://VEGA-627.vega-header.csssr.cloud/vega-header.js
=> VEGA-627: Исправить верстку хедера

.eslintrc.js, src/components/BaseHeader/BaseHeaderMenu/BaseHeaderMenu.test.tsx, src/components/BaseHeader/BaseHeaderMenu/BaseHeaderMenu.tsx, src/components/BaseHeader/BaseHeaderNav/BaseHeaderNav.tsx, src/components/Header/Header.tsx, src/components/Header/HeaderView.test.tsx, src/components/Header/HeaderView.tsx
=> VEGA-624: Покрыть тестами хедер

.eslintignore, .eslintrc.js, src/App/App.test.tsx, src/App/App.tsx, src/App/index.tsx, src/components/Header/HeaderView.test.tsx, src/components/Header/HeaderView.tsx
Cсылка в Jira CSSSR на задачу: https://jira.csssr.io/browse/VEGA-672
Ссылка на скрипт http://VEGA-672.vega-header.csssr.cloud/vega-header.js
Jira issue: VEGA-672
=> VEGA-672: Заменить роутер в vega-shell

.github/workflows/build-static.yaml, package.json, webpack.forShellConfig.js, yarn.lock
=> VEGA-728: Избавить от дублирования стилей vega-ui

src/App/App.tsx, src/components/Header/HeaderView.tsx
Jira issue: VEGA-2787
- добавлена ссылка на ФЭМ
=> VEGA-2787: Интеграция ФЭМ в обвязку

src/components/Header/Header.css, src/components/Header/HeaderView.tsx
=> VEGA-729: Добавить имя пользователя в хедер (РЕОП)

src/components/Header/HeaderView.tsx, src/components/Header/types.ts
=> VEGA-756: Восстановить подчеркивание таба Экономика проекта

.github/workflows/build-static.yaml, .github/workflows/continuous-integration.yml, .gitignore, codegen.yml, graphql.schema.json, src/App/index.tsx
=> VEGA-773: Разобраться с генерацией схемы

package.json, src/components/BaseHeader/BaseHeader.tsx, src/components/BaseHeader/BaseHeaderMenu/BaseHeaderMenu.test.tsx, src/components/BaseHeader/BaseHeaderMenu/BaseHeaderMenu.tsx, src/components/BaseHeader/BaseHeaderNav/BaseHeaderNav.test.tsx, src/components/BaseHeader/BaseHeaderNav/BaseHeaderNav.tsx, src/components/BaseHeader/Header.test.tsx, src/components/BaseHeader/types.ts, src/components/Header/HeaderView.tsx, src/components/Header/types.ts, yarn.lock
=> VEGA-689: Добавить data-test-id для хедера

graphql.schema.json, package.json, src/components/BaseHeader/BaseHeader.css, src/components/BaseHeader/BaseHeaderNav/BaseHeaderNav.tsx, yarn.lock
=> VEGA-730: Исправить смещение хедера при разрешении от 820

src/components/BaseHeader/BaseHeader.css
=> VEGA-843: Исправить верстку хедера
